<?php
/**
 * MetadataModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QuickPay
 *
 * QuickPay client to capture and refund payments
 *
 * OpenAPI spec version: v10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MetadataModelTest Class Doc Comment
 *
 * @category    Class */
// * @description MetadataModel
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MetadataModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MetadataModel"
     */
    public function testMetadataModel()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "bin"
     */
    public function testPropertyBin()
    {

    }

    /**
     * Test attribute "last4"
     */
    public function testPropertyLast4()
    {

    }

    /**
     * Test attribute "exp_month"
     */
    public function testPropertyExpMonth()
    {

    }

    /**
     * Test attribute "exp_year"
     */
    public function testPropertyExpYear()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

    /**
     * Test attribute "is_3d_secure"
     */
    public function testPropertyIs3dSecure()
    {

    }

    /**
     * Test attribute "issued_to"
     */
    public function testPropertyIssuedTo()
    {

    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {

    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {

    }

    /**
     * Test attribute "customer_ip"
     */
    public function testPropertyCustomerIp()
    {

    }

    /**
     * Test attribute "customer_country"
     */
    public function testPropertyCustomerCountry()
    {

    }

    /**
     * Test attribute "fraud_suspected"
     */
    public function testPropertyFraudSuspected()
    {

    }

    /**
     * Test attribute "fraud_remarks"
     */
    public function testPropertyFraudRemarks()
    {

    }

    /**
     * Test attribute "nin_number"
     */
    public function testPropertyNinNumber()
    {

    }

    /**
     * Test attribute "nin_country_code"
     */
    public function testPropertyNinCountryCode()
    {

    }

    /**
     * Test attribute "nin_gender"
     */
    public function testPropertyNinGender()
    {

    }

}
